# Generated by Django 5.2.3 on 2025-07-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatmessage_user_chatsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
